name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.schub.bar/actions/checkout@v7
      - uses: https://code.schub.bar/actions/docker-login-action@v4
        with:
          registry: code.schub.bar
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      - uses: https://code.schub.bar/actions/docker-build-push-action@v7
        id: docker_build
        with:
          context: .
          push: true
          tags: |
            code.schub.bar/${{ github.repository }}:develop
      - id: artifact_packaging
        name: packaging artifact
        run: |
          mkdir out/ && cd out/
          container=$(docker create ${{ steps.docker_build.outputs.imageid }})
          docker cp $container:/app .
          echo "version=$(./app/web --version | awk -F ' ' '{print $2}')" >> $GITHUB_OUTPUT
          cd app/ && tar -cvf ../smm-zerop.tar .
      - uses: https://code.schub.bar/actions/forgejo-upload-artifact@v5
        with:
          name: smm-zerop-${{ steps.artifact_packaging.outputs.version }}-linux-amd64.tar.zip
          path: ./out/smm-zerop.tar
